export { ProductFridgeIcon } from './productFridge'
export { CollapseUpIcon } from './collapseUp'
export { CollapseDownIcon } from './collapseDown'
export { CrayondLogoIcon } from './crayondLogo'
export { FilterIcon } from './filterIcon'
export { LogoutIcon } from './logoutIcon'
export { MailIcon } from './mailIcon'
export { MoreIcon } from './moreIcon'
export { NotifyBell } from './notifyBell'
export { PhoneIcon } from './phoneIcon'
export { ProdktLogo } from './prodktLogo'
export { ProductsIcon } from './productsIcon'
export { CloseIcon } from './closeIcon'
export { ServicesIcon } from './servicesIcon'
export { UserIcon } from './userIcon'
export { CategoryDummyIcon } from './categoryDummy'
export { InfoIcon } from './infoIcon'
export { InfoSmallIcon } from './infoSmall'
export { CopyIcon } from './copyIcon'



