export const productListStyle = {
  rootSx: {
    height: "calc(100vh - 14.7rem)",
    m: 2,
    borderRadius: 1.5,
    backgroundColor: 'primary.contrastText',
    p: 2,
  },
  mainBox: {
    //   margin: '2.4rem',
    //   p: '1.6rem',
    backgroundColor: "primary.contrastText",
    borderRadius: "1.2rem",
    display: "flex",
    justifyContent: "space-between",
    // flexDirection: "column",
    height: "calc(100vh - 17.8rem) !important",
    // overflow: "auto",
  },
  divider: {
    height: "3.2rem",
    marginInlineStart: "1.6rem",
    marginInlineEnd: "1.6rem",
  },
  gridbutton: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  addNewButton: {
    borderRadius: "0.8rem",
    backgroundColor: "primary.main",
    height: "4rem",
    boxShadow: "none",
    ":hover": {
      backgroundColor: "primary.main",
      boxShadow: "none",
    },
    textTransform: "capitalize",
    fontSize: "1.4rem",
    fontWeight: 500,
    lineHeight: "2rem",
    ml: 2,
  },
  uploadBtn: {
    borderRadius: "0.8rem",
    backgroundColor: "custom.main",
    height: "4rem",
    boxShadow: "none",
    color: 'primary.main',
    fontSize: "1.4rem",
    fontWeight: 500,
    lineHeight: "2rem",
    "&:hover": {
      backgroundColor: "custom.main",
      boxShadow: "none",
    },
    textTransform: "capitalize",
    border: "0.1rem solid",
    borderColor: 'primary.main'
  },
  filterIcon: {
    height: "4rem",
    width: "4rem",
    display: "grid",
    placeItems: "center",
    borderRadius: "0.8rem",
    cursor: "pointer",
    marginInlineStart: "1.6rem",
  },
  dialogmodal: {
    "& .MuiPaper-root": {
      borderRadius: "0.8rem",
      width: "100%",
    },
    "& .MuiDialogActions-root": {
      padding: "1.6rem",
      boxShadow: "0rem -0.2rem 1.6rem 0rem rgba(0, 0, 0, 0.08)",
    },
  },
  titleStyleDialog: {
    fontSize: "1.6rem",
    fontWeight: 600,
    color: "custom.onSurface",
  },
  dialogBodyStyle: {
    p: "1.6rem",
  },
  resetButtonSx: {
    width: "100%",
    borderRadius: "0.8rem",
    borderColor: "primary.main",
    color: "primary.main",
    textTransform: "capitalize",
    boxShadow: "none",
    height: "4rem",
    fontWeight: 500,
    fontSize: "1.4rem",
    ":hover": {
      boxShadow: "none",
      bgcolor: "#fff",
      color: "primary.main",
      borderColor: "primary.main",
    },
  },
  applyFilterButtonSx: {
    width: "100%",
    textTransform: "capitalize",
    backgroundColor: "primary.main",
    borderRadius: "0.8rem",
    boxShadow: "none",
    height: "4rem",
    fontWeight: 500,
    fontSize: "1.4rem",
    ":hover": {
      boxShadow: "none",
      backgroundColor: "primary.main",
    },
  },
  datePopoverStyle: {
    marginTop: "1rem",
    borderRadius: " 0.8rem",
    border: "0.1rem solid",
    borderColor: "custom.outlineVariant",
    minWidth: "31.4rem",
    overflow: "hidden",
  },

  selectChipHeaderTextSx: {
    fontSize: "1.4rem",
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: "2rem",
    color: "custom.onSurfaceVariant",
  },
  selectLabelStyle: {
    "&.Mui-error": {
      fontSize: "1.2rem",
    },
    " .MuiInputLabel-root": {
      fontSize: "1.8rem !important",
      color: "text.secondary",
      "& .MuiFormLabel-asterisk": {
        color: "red",
      },
    },
    "& .MuiFormControl-root": {
      "& .MuiTextField-root": {
        "& .MuiInputLabel-root": {
          fontSize: "2.2rem",
          color: "#000000",
        },
      },
    },
    '& .MuiAutocomplete-root .MuiFilledInput-root .MuiFilledInput-input': {
      fontSize: '1.4rem',
      color: 'text.primary',
      fontWeight: 500
    }
  },
  buttonItemContainer: {
    'display': 'flex',
    'cursor': 'pointer',
    'padding': '0rem',
    'borderRadius': '0.8rem',
    'justifyContent': 'center',
    'alignItems': 'center',
    'backgroundColor': 'primary.contrastText',
    ':hover': {
      borderColor: 'custom.outline',
      'backgroundColor': 'primary.contrastText',
    },
    'mr': -1.3,
  },
  badgeSx: {
    '& .MuiBadge-badge': {
      height: '0.6rem',
      minWidth: '0.6rem',
      left: '2.4rem',
      position: 'absolute',
      top: '1rem',
      width: '0.6rem',
    },
  },
  paginationCountTextStyle: {
    fontSize: "1.2rem",
    fontWeight: "400",
    lineHeight: "1.6rem",
    color: "text.secondary",
  },
  paginationBoxStyle: {
    '& .MuiSelect-icon': {
      top: '0.2rem',
      right: '-0.2rem',
    },
  },
  popoverStyle: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '1.6rem',
    borderRadius: '0.8rem',
    backgroundColor: 'primary.contrastText',
    gap: '1.2rem',
  },
  viewTextStyle: {
    cursor: 'pointer',
    color: 'text.primary',
    fontFamily: 'Sarabun',
    fontSize: '1.4rem',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '2rem',
  },
  headerContent: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'end',
  },
  uploadSx: {
    color: 'primary.main',
    textAlign: 'center',
    fontSize: '1.4rem',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '2rem',
    borderRadius: '0.8rem',
    height: '4.4rem',
    textTransform: 'capitalize',
  },
  addSx: {
    color: 'primary.contrastText',
    textAlign: 'center',
    fontSize: '1.4rem',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '2rem',
    borderRadius: '0.8rem',
    height: '4.4rem',
    textTransform: 'capitalize',
    backgroundColor: "primary.main",
    marginLeft: 2,
    boxShadow: 'none',
    ':hover': {
      boxShadow: 'none',
      backgroundColor: "primary.main",
    },
  },
  addNewSx: {
    color: 'primary.contrastText',
    textAlign: 'center',
    fontSize: '1.4rem',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '2rem',
    borderRadius: '0.8rem',
    height: '4rem',
    textTransform: 'capitalize',
    backgroundColor: "primary.main",
    boxShadow: 'none',
    mt: '5rem',
    ':hover': {
      boxShadow: 'none',
      backgroundColor: "primary.main",
    },
  },
  centerItem: {
    height: '60vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  productInfo: {
    fontSize: '1.6rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '2rem',
    color: 'text.primary',
    mt: 3
  },
  customerInfo: {
    fontSize: '1.6rem',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '2rem',
    color: 'text.secondary',
  },
  itemBox: {},
  textStyleSelect: {
    fontSize: "1.4rem",
    fontWeight: 500,
    color: "custom.onSurface",
    marginInline: "0.4rem",
  },
  pageSx: {
    height: '100%',
    alignItems: "flex-end",
    display: "grid"
  }
};
