Feature: Admin Portal
	Category

	Scenario: As an admin, I should be able to view, search, edit & add category

		Given I am on the page 'http://localhost:3000/login'
		When I set the auth token 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODkwLCJtb2JpbGVfbm8iOm51bGwsImlzX3ZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNzA0MTc2MzQ0LCJleHAiOjE3MDQ3ODExNDR9.64QaI5pZg0Tma3nESBOfK82_IM2UwHS4o8A_7PM1iEY' in 'authToken' to the local storage
		Then I go to 'http://localhost:3000/categories'
		Then I wait for 3 seconds
		Then I click the element 'navbar1'
		Then I click the element 'subNav1'
		And I should see 'Categories (41)'
		Then I should see 'Mobile'
		And I should see 'View Specifications'
		Then I should see 'Laptop'
		Then I should see 'View Specifications'
		Then I should see 'Earphone/ headphone'
		And I should see 'View Specifications'
		When I click the element 'viewSpecifications0'
		Then I should see 'Specifications'
		And I should see 'Mobile'
		Then I should see 'Brand Name'
		Then I should see 'Model Number'
		Then I should see 'RAM'
		Then I should see 'Storage'
		When I click the 'Edit Category Details'
		Then I should see 'Edit Category Details'
		Then I should see 'Mobile' in the field 'category_name'
		Then I should see 'Phone_1683191656914.png'
		Then I should see 'Mobile@2x_1683781814276.png'
		Then I click the element 'customize'
		Then I type 'Stars' in the 'customize'
		Then I should not see '12345qwert' in the 'serialNo'
		Then I should see 'Yes1' checked
		Then I should see 'Yes2' checked
		Then I should see 'No3' checked
		When I click the element 'updateCategory'
		Then I wait for 3 seconds
		Then I should see 'upsert product category Successfully!'
		Then I click the element 'search'
		And I type 'Laptop' in the 'search'
		Then I should see 'Laptop'
		Then I wait for 1 seconds
		And I dont want to see 'Chimney'
		And I dont want to see 'Water Purifier'
		And I dont want to see 'Washing Machine'
		Then I click the element 'addCategory'
		Then I should see 'Add New Category'
		When I click the element 'updateCategory'
		Then I should see 'category name required'
		Then I click the element 'category_name'
		And I type 'Mobile' in the 'category_name'
		Then I should see 'Mobile' in the field 'category_name'
		Then I click the element 'options'
		Then I should see 'Electronics'
		And I click the 'Upload'
		Then I upload 'chatExplore.png' to the element 'uploadImg'
		Then I upload 'product.png' to the element 'uploadIcon'
		Then I type '12345qwert' in the 'serialNo'
		Then I should see 'Add Fields'
		And I click the element 'customize'
		And I type 'Storage' in the 'customize'
		Then I should see 'Coverage Details'
		Then I tick the 'Yes1'
		Then I tick the 'Yes2'
		Then I tick the 'No3'
		When I click the element 'updateCategory'
		Then I should see 'upsert product category Successfully!'
		When I click the 'addCategory'
		Then I should see 'Add New Category'
		When I click the element 'close'
		Then I dont want to see 'Add New Category'
