@Fe-c820b5cb
Feature: Brand Portal - Manage  Customers
	As a user, I should be able to bulk upload customer details

	@Sc-63d1285a
	Scenario: As a user, I should be able to add customer segment  view, edit and delete the added customer segments
	    Given I am on the page 'http://localhost:3001/login'
		Then I set the auth token 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OTEwLCJtb2JpbGVfbm8iOiIyMjIyMjIyMjIyIiwiaXNfdmVyaWZpZWQiOmZhbHNlLCJpYXQiOjE3MTc1MDE3MDIsImV4cCI6MTcxODEwNjUwMn0.62ZD-Q6vSKHXVyD3eQI-uP4aFVrA65SsPqA4r2GkqIc' in 'authToken' to the local storage
		Then I go to 'http://localhost:3001/customers/manage-segments'
		Then I should see 'Customer segments' in the element 'title'
		Then I should see 'Give an unique tag to group the customers'
		And I focus the 'Add new tag'
		When I click the 'Add new tag'
		Then I should see 'Add new tag'
		Then I click the element 'close'
		When I click the 'Add new tag'
		Then I should see 'Add new tag'
		When I click the 'Save'
		Then I should see 'Enter a tag name'
		Then I type 'Premium' in the field 'name'
		When I click the 'Save'
		Then I should see 'New tag is created'
		Then I should see 'Tag name'
		Then I should see 'Created on'
		Then I should see 'Updated on'
		Then I should see 'Premium'
		Then I should see '20-02-2020, 07:00 PM'
		Then I should see '20-02-2020, 07:00 PM'
		Then I should see the element 'menu1'
		When I click the element 'menu1'
		Then I should see 'Edit'
		Then I should see 'Delete'
		Then I press the key 'ArrowDown'
		Then I press the key 'ArrowDown'
		And I press the key 'Enter'
		Then I should see 'Edit tag'
		When I click the element 'close1'
		Then I dont want to see the 'Edit tag'
		When I click the element 'menu1'
		Then I press the key 'ArrowDown'
		And I press the key 'Enter'
		Then I should see 'Edit tag'
		Then The element 'update' should be disabled
		Then I clear the field 'name'
		Then I type 'VIP' in the field 'name'
		And I click the 'Update'
		Then I should see 'Updated'
		When I click the element 'menu1'
		Then I press the key 'ArrowDown'
		Then I press the key 'ArrowDown'
		And I press the key 'Enter'
		When I should see 'Are you sure , you want to delete'
		When I clear the 'Cancel'
		Then I dont want to see the 'Are you sure , you want to delete'
		When I click the element 'menu1'
		Then I press the key 'ArrowDown'
		Then I press the key 'ArrowDown'
		And I press the key 'Enter'
		When I should see 'Are you sure , you want to delete'
		When I click the 'Delete'
		Then I should see 'Deleted'