export const webRoutes = {
  login: '/login',
  home: '/',
  signin: '/signin',
  verification: '/verification',
  userDetails: '/tellaboutyourself',
  otpSuccessfully: '/otpsuccessfully',
  productCategory: '/productCategory',
  signupSuccessful: '/signupSuccessful',
  specifications: '/specifications',
  searchproduct: '/searchproduct',
  nickName: '/nickName',
  productSummary: '/productSummary',
  productAddedSuccessfully: '/productaddedsuccessfully',
  secureProduct: '/secureProduct',
  addProductDetails: '/addProductDetails',
  productDetails: '/productDetails/:product_id',
  userProfile: '/userProfile',
  editProfile: '/editProfile',
  amcDetails: '/amcDetails/:product_id',
  activityLogs: '/activityLogs/:product_id',
  shareDetails: '/shareDetails',
  serviceHistory: '/serviceHistory',
  warrantyDetails: '/warrantyDetails/:product_id',
  insuranceDetails: '/insuranceDetails/:product_id',
  availableAmc: '/availableAmc/:product_id',
  extendedWarranty: '/extendedWarranty/:product_id',
  amcPurchase: '/amcPurchase',
  chooseProduct: '/chooseProduct',
  chooseServiceProviders: '/chooseServiceProviders',
  manageServiceProviders: '/manageServiceProviders',
  bookServiceProviderSuccessfully: '/bookServiceProviderSuccessfully',
  emailVerification: '/emailVerification',
  availableInsurance: '/availableInsurance/:product_id',
  whatsAppVerification: '/whatsAppVerification',
  availableWarranty: '/availableWarranty/:product_id',
  addproductBot: '/addproductBot',
  addCoverageDetails: '/addCoverageDetails',
  captureImageToAddProduct: '/captureImageToAddProduct',
  uploadedgallery: '/uploadedgallery',
  chatBotAmc: '/chatBotAmc/:product_id',
  chatBotWarranty: '/chatBotWarranty/:product_id',
  chatBotExtendedWarranty: '/chatBotExtendedWarranty/:product_id',
  chatBotInsurance: '/chatBotInsurance/:product_id',
  viewProductDocument: '/viewProductDocument/:product_id',
  feedbackReport: '/feedbackReport',
  chatBotProductDetails: '/chatBotProductDetails/:product_id',
  scheduleServiceReminder: '/scheduleServiceReminder',
  recordScheduleService: '/recordScheduleService',
  preferredServiceProvider: '/preferredServiceProvider',
  privacyPolicy: '/privacyPolicy',
  archivedProducts: '/archivedProducts',
  completeWhatsAppAddProduct: '/completeWhatsAppAddProduct',

  karmacalculator:'/karmaCalculator',
  questionsFlows:"/QuestinsFlows",
  chooseVehicles:"/chooseVehicles",
  chooseFuel:"/chooseFuel",
  driveKm:"/driveKm",
  normalyEate:"/normalyEate",
  homeAppliance:"/homeAppliance",
  consumeElectricity:"/consumeElectricity",
  summary:"/summary",
  plantNowOffset:'/plantNowOffset',
  successMessage:"/successMessage"
};
