Feature: Scan flow - Upload

    User should be able to upload multiple images/pdf if required


    Scenario: As a user, I should be able to upload invoice and add the product
        Given I am on the page 'http://localhost:3000/signin'
        When I set the auth token 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzQ4LCJtb2JpbGVfbm8iOiI5NTE0Nzk3MTk0IiwiaXNfdmVyaWZpZWQiOmZhbHNlLCJpYXQiOjE2OTUxOTA2OTYsImV4cCI6MTY5NTI3NzA5Nn0.0HYnkAOBAG8KMU21cFroe35AmIWG_eB8t4wTDvW8IcM' in 'authToken' to the local storage
        Then I go to 'http://localhost:3000/'
        And  I wait for 12 seconds
        # Then I focus the element 'addProduct'
        When I click the element 'addNewProduct'
        Then I should see 'Add Product'
        Then I should see 'Scan/Upload'
        When I click the element 'scan'
        # Then I wait for the network response 'http://localhost:3000/addproductBot'
        Then I should see 'Add product in a single go!'
        Then I should see 'Upload Invoice purchase & policy documents'
        Then I upload 'invoice.pdf' to the element 'bot-invoice'
        Then I should see 'Uploaded Files'
        When I click the element 'close'
        Then I upload 'invoice.pdf' to the element 'bot-invoice'
        Then I should see 'Uploaded Files'
        When I click the element 'proceed'
        Then I wait for the network response 'https://dev-api.prodkt.co/api/v1/ai/scan_for_add_product' for 30 seconds
        Then I should see 'Our document- fetching squad is on the case, retrieving the file you uploaded.'
        And I wait for 3 seconds
        Then I should see 'Fetching invoice documents details...'
        And I wait for 3 seconds
        Then I should see 'Mission accomplished! Document fetched successfully'
        And I wait for  seconds
        Then I should see 'Choose the product that you want to add'
        Then I should see 'Haier 165 Litre 1 Star Direct Cool Single Door Refrigerator'
        Then I should see 'Haier 165 Litre 3 Star Direct Cool Single Door Refrigerator'
        Then I tick the 'y1'
        Then I should see 'Product Details'
        Then I should see 'Haier 165 Litre 1 Star Direct Cool Single Door Refrigerator'
        When I click the element 'previous2'
        Then I should see 'Choose the product that you wan to add'
        Then I tick the 'y1'
        And I should see 'Product Details'
        Then I should see 'Haier 165 Litre 1 Star Direct Cool Single Door Refrigerator'
        Then The element 'proceed' should be disabled
        Then I type '11111' in the 'serialNumber'
        Then I type '11111' in the 'imeiNumber'
        And The element 'proceed' should be enabled
        And I click the element 'proceed'
        Then I should see 'Add coverage details'
        Then I focus the element 'previous'
        When I click the element 'previous'
        Then I should see 'Add Product'
        Then I should see 'Upload invoice purchase & policy documents'
        When I click the element 'upload'
        Then I upload '' to the element 'upload'
        Then I should see 'Upload Files'
        When I click the element 'proceed'
        Then I should see 'Our document- fetching squad is on the case, retrieving the file you uploaded.'
        And I wait for 3 seconds
        Then I should see 'Fetching invoice documents details...'
        And I wait for 3 seconds
        Then I should see 'Mission accomplished! Document fetched successfully'
        And I wait for 2 seconds
        Then I should see 'Choose the product that you want to add'
        Then I tick the 'y1'
        And I should see 'Product Details'
        Then I should see 'Haier 165 Litre 1 Star Direct Cool Single Door Refrigerator'
        Then The element 'proceed' should be disabled
        Then I type '11111' in the 'serialNumber'
        Then I type '11111' in the 'imeiNumber'
        And The element 'proceed' should be enabled
        And I click the element 'proceed'
        Then I should see 'Add coverage details'
        Then I should see 'Product is under warranty till 15 Sep, 2023'
        Then I should see 'SAMSUNG 324 L Frost Free Double Door 3 Star Convertible Refrigerator...'
        Then I should see 'Under Extended Warranty'
        And I should see 'Insurance Protected'
        Then I should see 'AMC Covered'
        When I click the element 'yes1'
        Then The value of the attribute 'data-yes1' in the element 'yes1' should be 'active'
        When I click the element 'no1'
        Then The value of the attribute 'data-no1' in the element 'no1' should be 'active'
        When I click the element 'yes2'
        Then The value of the attribute 'data-yes2' in the element 'yes2' should be 'active'
        When I click the element 'no3'
        Then The value of the attribute 'data-no3' in the element 'no3' should be 'active'
        And The element 'next' should be enabled
        When I click the 'next'
        Then I should see 'Product Summary'
        When I click the element 'previous1'
        Then I should see 'Add coverage details'
        Then I should see 'Product is under warranty till 15 Sep, 2023'
        When I click the 'next'
        Then I should see 'Product Summary'
        And I should see 'SAMSUNG 324 L Frost Free Double Door 3 Star Convertible Refrigerator (Elegant Inox, RT34T4513S8/HL)'
        Then I should see 'Product Details'
        And I should see 'Date of Purchase'
        And I should see '25-Mar-2023'
        Then I should see 'Serial Number'
        And I should see '0254861475'
        Then I should see 'Model Number'
        And I should see '6789654'
        Then I should see 'Mode of Purchase'
        And I should see 'Offline'
        Then I should see 'Location'
        And I should see 'Neelankarai, Chennai, Tamilnadu'
        Then I should see 'Coverage Details'
        And I should see 'Brand Warranty'
        Then I should see '12 Months Coverage'
        And I should see 'Under Extended Warranty'
        Then I should see 'Insurance Protected'
        And I should see 'AMC Covered'
        Then The value of the attribute 'data-no1' in the element 'no1' should be 'active'
        Then The value of the attribute 'data-yes2' in the element 'yes2' should be 'active'
        Then The value of the attribute 'data-no3' in the element 'no3' should be 'active'
        When I click the element 'yes1'
        Then The value of the attribute 'data-yes1' in the element 'yes1' should be 'active'
        When I click the element 'next1'
        Then I wait for the network response 'www.prodkt.cpm/nickname'
        And I should see 'Give your device a quirky nickname!'
        And I should see 'Kitchen Fridge'
        And I should see 'Double Doo Fridge'
        And I should see 'Old Fridge'
        And I should see 'Home Fridge'
        When I click the element 'nickname2'
        Then I should see 'Double Doo Fridge' in the 'nickname'
        Then I clear the field 'nickname'
        And I type 'Mr. Fridge' in the 'nickname'
        When I click the element 'nextArrow'
        Then I wait for the network response 'www.prodkt.cpm/succesfull'
        And I should see 'Mr. Fridge'
        And I should see 'SAMSUNG 324 L Frost Free Double Door 3 Star Convertible Refrigerator (Elegant Inox, RT34T4513S8/HL)'
        Then I wait for 2 seconds
        Then I should see 'Shedule periodic service reminder'